# This template file should be left untouched 
# The app will in order:
# 1. Read this file (template.config.toml)
# 2. Overwrite the settings with those in file config.toml (it it exists)
# 3. Overwrite the settings with environment variables called "MYAIR_INFLUX_<SECTION>_<KEY>" (with section and key uppercase), if these exist.
#    For example, set the env var MYAIR_INFLUX_MAIN_LOGVERBOSITY to DEBUG to overwrite the log verbosity

[resmed]
login = "resmed user e-mail" # As entered on https://myair2.resmed.com/ or in the myAir app
password = "resmed password" # As entered on https://myair2.resmed.com/ or in the myAir app
region = "NA"                # Either NA (for North America) or EU (for Europe)
# Max number of days of historical data to query. Note = app may end up downloading more days because resmed's API have a month granularity
max_days = 365

[influx]
url = "http://localhost:8086"
bucket = "Resmed"           # Name of bucket to use in influx db
measurement = "cpap"        # Name of measurement
token = "super-secret-token"
org = "your org in influx"

[main]
logverbosity = "INFO" # By increasing level of verbosity = FATAL, ERROR, WARNING, INFO, DEBUG
loop_minutes = 60     # How often to pull data from resmed. 0 to pull only once
